name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Используйте более новые версии

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Используйте более новую версию setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r CarWashing/requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: django-insecure-55_4^n6dqjolsrmrr@&87=(zu$dc_s8jo+l^eg!pqtapfnnx2-
        DB_NAME: CarWash
        DB_USER: postgres
        DB_PASSWORD: 25122002
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
        DEBUG_MODE: False
      run: |
        py manage.py test
